/** Every event and command of the wire by its type, and its schema. */

import {
  AgentConfigureSchema,
  AgentDrainSchema,
  AgentRegisterSchema,
  AgentReplySchema,
  AgentSaySchema,
  CallAttentionSchema,
  CallCallbackSchema,
  CallOptOutSchema,
  CallClaimSchema,
  CallDialSchema,
  CallDtmfSchema,
  CallEventSchema,
  CallHangupSchema,
  CallHoldSchema,
  CallLogSchema,
  CallMuteSchema,
  CallTransferSchema,
  CallUnholdSchema,
  CallUnmuteSchema,
  DevAnswerSchema,
  ParticipantMuteSchema,
  ParticipantRemoveSchema,
  PingSchema,
  PromptSetSchema,
  RoomInviteSchema,
  RoomSendSchema,
  SessionConfigureSchema,
  StateSetSchema,
  SupervisorVerbSchema,
  ToolsSetSchema,
} from "./commands.js";
import { ToolResultSchema } from "./defs.js";
import {
  AttentionAnsweredSchema,
  AttentionRequestedSchema,
  CodeClaimedSchema,
  CodeIssuedSchema,
  ConfirmDeclinedSchema,
  ConfirmGrantedSchema,
  ConfirmRequestSchema,
  CreditsExhaustedSchema,
  CustomSchema,
  DevRequestSchema,
  DocsSourcesSchema,
  DtmfReceivedSchema,
  ErrorEventSchema,
  FleetFullSchema,
  LogCaughtUpSchema,
  LogGapSchema,
  MemoryOpsSchema,
  MessageTakenSchema,
  MessageWaitingSchema,
  PongSchema,
  PromptChangedSchema,
  StateChangedSchema,
  SupervisorEndedSchema,
  SupervisorReleasedSchema,
  SupervisorSaidSchema,
  SupervisorTookOverSchema,
  SupervisorTransferredSchema,
  SupervisorWhisperedSchema,
  ToolCallSchema,
  ToolsChangedSchema,
  UserStateChangedSchema,
  UserTranscriptSchema,
  UserTurnEndedSchema,
} from "./events.js";
import {
  AgentConfiguredSchema,
  AgentDetachedSchema,
  AgentDrainingSchema,
  AgentRegisteredSchema,
  AgentStateChangedSchema,
  AgentTranscriptSchema,
  AgentTurnEndedSchema,
  CallAttachedSchema,
  CallbackRequestedSchema,
  CallClaimedSchema,
  CallDialingSchema,
  CallEndedSchema,
  CallLineSchema,
  CallRingingSchema,
  CallScoreSchema,
  CallStartedSchema,
  CallSummarySchema,
  CallTransferredSchema,
} from "./events-call.js";
import {
  AvatarMetricsSchema,
  EOTInferenceMetricsSchema,
  EOUMetricsSchema,
  InterruptionMetricsSchema,
  LLMMetricsSchema,
  RealtimeModelMetricsSchema,
  STTMetricsSchema,
  TTSMetricsSchema,
  VADMetricsSchema,
} from "./metrics.js";
import {
  EventReceivedSchema,
  ParticipantJoinedSchema,
  ParticipantLeftSchema,
  ParticipantSpeakingSchema,
  RoomOpenedSchema,
  RoomSentSchema,
  TrackPublishedSchema,
  TrackUnpublishedSchema,
} from "./room.js";

/** Every event by its wire type; the codec looks the schema up here. */
export const EVENT_SCHEMAS = {
  "agent.configured": AgentConfiguredSchema,
  "agent.detached": AgentDetachedSchema,
  "agent.draining": AgentDrainingSchema,
  "agent.registered": AgentRegisteredSchema,
  "agent.state": AgentStateChangedSchema,
  "agent.transcript": AgentTranscriptSchema,
  "attention.answered": AttentionAnsweredSchema,
  "attention.requested": AttentionRequestedSchema,
  "call.attached": CallAttachedSchema,
  "call.claimed": CallClaimedSchema,
  "call.dialing": CallDialingSchema,
  "call.ended": CallEndedSchema,
  "call.line": CallLineSchema,
  "call.ringing": CallRingingSchema,
  "call.score": CallScoreSchema,
  "call.started": CallStartedSchema,
  "call.summary": CallSummarySchema,
  "call.transferred": CallTransferredSchema,
  "callback.requested": CallbackRequestedSchema,
  "code.claimed": CodeClaimedSchema,
  "code.issued": CodeIssuedSchema,
  "confirm.declined": ConfirmDeclinedSchema,
  "confirm.granted": ConfirmGrantedSchema,
  "confirm.request": ConfirmRequestSchema,
  "credits.exhausted": CreditsExhaustedSchema,
  "custom": CustomSchema,
  "dev.request": DevRequestSchema,
  "docs.sources": DocsSourcesSchema,
  "dtmf.received": DtmfReceivedSchema,
  "error": ErrorEventSchema,
  "event.received": EventReceivedSchema,
  "fleet.full": FleetFullSchema,
  "log.caught_up": LogCaughtUpSchema,
  "log.gap": LogGapSchema,
  "memory.ops": MemoryOpsSchema,
  "message.taken": MessageTakenSchema,
  "message.waiting": MessageWaitingSchema,
  "metrics.avatar": AvatarMetricsSchema,
  "metrics.eot": EOTInferenceMetricsSchema,
  "metrics.eou": EOUMetricsSchema,
  "metrics.interruption": InterruptionMetricsSchema,
  "metrics.llm": LLMMetricsSchema,
  "metrics.realtime": RealtimeModelMetricsSchema,
  "metrics.stt": STTMetricsSchema,
  "metrics.tts": TTSMetricsSchema,
  "metrics.vad": VADMetricsSchema,
  "participant.joined": ParticipantJoinedSchema,
  "participant.left": ParticipantLeftSchema,
  "participant.speaking": ParticipantSpeakingSchema,
  "pong": PongSchema,
  "prompt.changed": PromptChangedSchema,
  "room.opened": RoomOpenedSchema,
  "room.sent": RoomSentSchema,
  "state.changed": StateChangedSchema,
  "supervisor.ended": SupervisorEndedSchema,
  "supervisor.released": SupervisorReleasedSchema,
  "supervisor.said": SupervisorSaidSchema,
  "supervisor.took_over": SupervisorTookOverSchema,
  "supervisor.transferred": SupervisorTransferredSchema,
  "supervisor.whispered": SupervisorWhisperedSchema,
  "tool.call": ToolCallSchema,
  "tool.result": ToolResultSchema,
  "tools.changed": ToolsChangedSchema,
  "track.published": TrackPublishedSchema,
  "track.unpublished": TrackUnpublishedSchema,
  "turn.agent": AgentTurnEndedSchema,
  "turn.user": UserTurnEndedSchema,
  "user.state": UserStateChangedSchema,
  "user.transcript": UserTranscriptSchema,
} as const;

export type EventType = keyof typeof EVENT_SCHEMAS;

/** Events a store may drop and a slow reader may miss: the entry's ephemeral flag defaults to this. */
export const EPHEMERAL_EVENTS: ReadonlySet<EventType> = new Set<EventType>(["agent.transcript", "dev.request", "log.caught_up", "log.gap", "metrics.vad", "participant.speaking", "pong", "room.sent", "user.transcript"]);

/** Every command by its wire type; the codec looks the schema up here. */
export const COMMAND_SCHEMAS = {
  "agent.configure": AgentConfigureSchema,
  "agent.drain": AgentDrainSchema,
  "agent.register": AgentRegisterSchema,
  "agent.reply": AgentReplySchema,
  "agent.say": AgentSaySchema,
  "call.attention": CallAttentionSchema,
  "call.callback": CallCallbackSchema,
  "call.claim": CallClaimSchema,
  "call.dial": CallDialSchema,
  "call.dtmf": CallDtmfSchema,
  "call.event": CallEventSchema,
  "call.hangup": CallHangupSchema,
  "call.hold": CallHoldSchema,
  "call.log": CallLogSchema,
  "call.mute": CallMuteSchema,
  "call.opt_out": CallOptOutSchema,
  "call.transfer": CallTransferSchema,
  "call.unhold": CallUnholdSchema,
  "call.unmute": CallUnmuteSchema,
  "dev.answer": DevAnswerSchema,
  "participant.mute": ParticipantMuteSchema,
  "participant.remove": ParticipantRemoveSchema,
  "ping": PingSchema,
  "prompt.set": PromptSetSchema,
  "room.invite": RoomInviteSchema,
  "room.send": RoomSendSchema,
  "session.configure": SessionConfigureSchema,
  "state.set": StateSetSchema,
  "supervisor.verb": SupervisorVerbSchema,
  "tool.result": ToolResultSchema,
  "tools.set": ToolsSetSchema,
} as const;

export type CommandType = keyof typeof COMMAND_SCHEMAS;
